// ────────────────────────────────────────────────────────────────────
//  Centralised API service layer for the HMS
//  Every module imports from here — no direct supabase calls in pages
// ────────────────────────────────────────────────────────────────────
import { supabase } from '../lib/supabase';

// ── helpers ──────────────────────────────────────────────────────────
const throwIf = ({ data, error }) => {
  if (error) throw error;
  return data;
};

// ═══════════════════════════════════════════════════════════════════
// PATIENTS
// ═══════════════════════════════════════════════════════════════════
export const patientService = {
  /** Fetch all patients ordered by most recent */
  async list({ search = '' } = {}) {
    let q = supabase
      .from('patients')
      .select('*')
      .order('created_at', { ascending: false });

    if (search) {
      q = q.or(
        `first_name.ilike.%${search}%,last_name.ilike.%${search}%,patient_no.ilike.%${search}%,phone.ilike.%${search}%`
      );
    }
    return throwIf(await q);
  },

  async get(id) {
    return throwIf(await supabase.from('patients').select('*').eq('id', id).single());
  },

  async create(payload) {
    // patient_no autogenerated by DB trigger
    return throwIf(
      await supabase.from('patients').insert([payload]).select().single()
    );
  },

  async update(id, payload) {
    return throwIf(
      await supabase.from('patients').update(payload).eq('id', id).select().single()
    );
  },

  async count() {
    const { count } = await supabase.from('patients').select('*', { count: 'exact', head: true });
    return count || 0;
  },
};

// ═══════════════════════════════════════════════════════════════════
// OPD VISITS / TRIAGE / QUEUE
// ═══════════════════════════════════════════════════════════════════
export const opdService = {
  /** Today's OPD queue via the DB view */
  async getQueue() {
    return throwIf(
      await supabase.from('v_opd_queue_today').select('*')
    );
  },

  /** Create a new triage visit */
  async createVisit(payload) {
    return throwIf(
      await supabase.from('opd_visits').insert([payload]).select().single()
    );
  },

  /** Get a single visit with patient info */
  async getVisit(id) {
    return throwIf(
      await supabase
        .from('opd_visits')
        .select('*, patients(*)')
        .eq('id', id)
        .single()
    );
  },

  /** Update visit status */
  async updateStatus(id, status) {
    return throwIf(
      await supabase.from('opd_visits').update({ status }).eq('id', id)
    );
  },

  /** Get queue count for dashboard */
  async todayCount() {
    const today = new Date().toISOString().slice(0, 10);
    const { count } = await supabase
      .from('opd_visits')
      .select('*', { count: 'exact', head: true })
      .eq('visit_date', today);
    return count || 0;
  },
};

// ═══════════════════════════════════════════════════════════════════
// CONSULTATIONS
// ═══════════════════════════════════════════════════════════════════
export const consultationService = {
  async create(payload) {
    return throwIf(
      await supabase.from('consultations').insert([payload]).select().single()
    );
  },

  async update(id, payload) {
    return throwIf(
      await supabase.from('consultations').update(payload).eq('id', id)
    );
  },

  async getByVisit(visitId) {
    return throwIf(
      await supabase.from('consultations').select('*').eq('visit_id', visitId).maybeSingle()
    );
  },

  /** Create prescription + items */
  async createPrescription(prescriptionPayload, items) {
    const rx = throwIf(
      await supabase.from('prescriptions').insert([prescriptionPayload]).select().single()
    );
    if (items?.length) {
      throwIf(
        await supabase.from('prescription_items').insert(
          items.map(i => ({ ...i, prescription_id: rx.id }))
        )
      );
    }
    return rx;
  },
};

// ═══════════════════════════════════════════════════════════════════
// LAB ORDERS
// ═══════════════════════════════════════════════════════════════════
export const labService = {
  /** All lab orders for today */
  async list({ status = null } = {}) {
    let q = supabase
      .from('lab_orders')
      .select(`
        *,
        patients(patient_no, first_name, last_name, age, gender),
        lab_order_items(*)
      `)
      .order('ordered_at', { ascending: false });

    if (status) q = q.eq('status', status);
    return throwIf(await q);
  },

  async create(orderPayload, tests = []) {
    const order = throwIf(
      await supabase.from('lab_orders').insert([orderPayload]).select().single()
    );
    if (tests.length) {
      throwIf(
        await supabase.from('lab_order_items').insert(
          tests.map(t => ({ lab_order_id: order.id, test_name: t, status: 'pending' }))
        )
      );
    }
    return order;
  },

  async updateStatus(id, status) {
    return throwIf(
      await supabase.from('lab_orders').update({ status }).eq('id', id)
    );
  },

  /** Save results for specific test items */
  async saveResults(orderId, items) {
    // items: [{ id, result }]
    const updates = items.map(i =>
      supabase.from('lab_order_items').update({ result: i.result, status: 'completed', result_at: new Date().toISOString() }).eq('id', i.id)
    );
    await Promise.all(updates);
    // Mark order as completed
    await supabase.from('lab_orders').update({ status: 'completed' }).eq('id', orderId);
  },

  async pendingCount() {
    const { count } = await supabase
      .from('lab_orders')
      .select('*', { count: 'exact', head: true })
      .eq('status', 'pending');
    return count || 0;
  },
};

// ═══════════════════════════════════════════════════════════════════
// PHARMACY
// ═══════════════════════════════════════════════════════════════════
export const pharmacyService = {
  /** Pending prescriptions with items */
  async listPrescriptions() {
    return throwIf(
      await supabase
        .from('prescriptions')
        .select(`
          *,
          patients(patient_no, first_name, last_name),
          prescription_items(*),
          consultations(visit_id, opd_visits(assigned_doctor_id, users(first_name, last_name)))
        `)
        .order('prescribed_at', { ascending: false })
    );
  },

  /** Drug stock — aggregate by drug_catalog */
  async listDrugStock() {
    return throwIf(
      await supabase
        .from('drug_catalog')
        .select(`
          *,
          drug_stock(quantity, expiry_date, batch_no)
        `)
        .eq('is_active', true)
        .order('name')
    );
  },

  /** Dispense: update quantity_dispensed on items + mark status */
  async dispense(prescriptionId, itemUpdates, allDone) {
    for (const upd of itemUpdates) {
      await supabase
        .from('prescription_items')
        .update({ quantity_dispensed: upd.dispensed })
        .eq('id', upd.id);
    }
    await supabase
      .from('prescriptions')
      .update({ status: allDone ? 'dispensed' : 'partial', dispensed_at: new Date().toISOString() })
      .eq('id', prescriptionId);
  },
};

// ═══════════════════════════════════════════════════════════════════
// INVENTORY
// ═══════════════════════════════════════════════════════════════════
export const inventoryService = {
  async list({ category = null, search = '' } = {}) {
    let q = supabase
      .from('inventory_items')
      .select('*')
      .eq('is_active', true)
      .order('name');

    if (category) q = q.eq('category', category);
    if (search)   q = q.ilike('name', `%${search}%`);
    return throwIf(await q);
  },

  async receive(itemId, qty, meta) {
    // Increment qty
    const { data: item } = await supabase.from('inventory_items').select('current_qty').eq('id', itemId).single();
    await supabase.from('inventory_items').update({ current_qty: (item?.current_qty || 0) + qty }).eq('id', itemId);
    // Log transaction
    await supabase.from('inventory_transactions').insert([{
      item_id: itemId,
      txn_type: 'receive',
      quantity: qty,
      supplier: meta.supplier,
      batch_no: meta.batchNo,
      expiry_date: meta.expiry || null,
      cost: parseFloat(meta.cost) || 0,
      performed_by: meta.userId,
    }]);
  },

  async issue(itemId, qty, meta) {
    const { data: item } = await supabase.from('inventory_items').select('current_qty').eq('id', itemId).single();
    await supabase.from('inventory_items').update({ current_qty: Math.max(0, (item?.current_qty || 0) - qty) }).eq('id', itemId);
    await supabase.from('inventory_transactions').insert([{
      item_id: itemId,
      txn_type: 'dispense',
      quantity: qty,
      department_id: meta.deptId || null,
      performed_by: meta.userId,
      notes: meta.notes || '',
    }]);
  },

  async transactions() {
    return throwIf(
      await supabase
        .from('inventory_transactions')
        .select('*, inventory_items(name), departments(name)')
        .order('txn_at', { ascending: false })
        .limit(50)
    );
  },
};

// ═══════════════════════════════════════════════════════════════════
// WARDS / BEDS / ADMISSIONS
// ═══════════════════════════════════════════════════════════════════
export const ipdService = {
  async getBedOccupancy() {
    return throwIf(await supabase.from('v_bed_occupancy').select('*'));
  },

  async listBeds(wardId = null) {
    let q = supabase
      .from('beds')
      .select('*, wards(name, ward_type), admissions(*, patients(first_name, last_name, patient_no, age, gender))')
      .eq('admissions.status', 'active');
    if (wardId) q = q.eq('ward_id', wardId);
    return throwIf(await q);
  },

  async listAdmissions() {
    return throwIf(
      await supabase.from('v_current_inpatients').select('*')
    );
  },

  async admit(payload) {
    // Update bed status
    if (payload.bed_id) {
      await supabase.from('beds').update({ status: 'occupied' }).eq('id', payload.bed_id);
    }
    return throwIf(
      await supabase.from('admissions').insert([payload]).select().single()
    );
  },

  async discharge(admissionId, payload) {
    const { data: adm } = await supabase.from('admissions').select('bed_id').eq('id', admissionId).single();
    if (adm?.bed_id) {
      await supabase.from('beds').update({ status: 'available' }).eq('id', adm.bed_id);
    }
    return throwIf(
      await supabase.from('admissions')
        .update({ status: 'discharged', discharged_at: new Date().toISOString(), ...payload })
        .eq('id', admissionId)
    );
  },

  async addNote(payload) {
    return throwIf(
      await supabase.from('clinical_notes').insert([payload]).select().single()
    );
  },

  async addVitals(payload) {
    return throwIf(
      await supabase.from('vitals_records').insert([payload]).select().single()
    );
  },

  async getVitals(patientId, admissionId) {
    return throwIf(
      await supabase
        .from('vitals_records')
        .select('*')
        .eq('patient_id', patientId)
        .eq('admission_id', admissionId)
        .order('recorded_at', { ascending: false })
        .limit(20)
    );
  },

  async activeCount() {
    const { count } = await supabase
      .from('admissions')
      .select('*', { count: 'exact', head: true })
      .eq('status', 'active');
    return count || 0;
  },
};

// ═══════════════════════════════════════════════════════════════════
// BILLING
// ═══════════════════════════════════════════════════════════════════
export const billingService = {
  async list({ status = null, search = '' } = {}) {
    let q = supabase
      .from('bills')
      .select('*, patients(patient_no, first_name, last_name), bill_items(*), payments(*)')
      .order('created_at', { ascending: false });

    if (status) q = q.eq('status', status);
    if (search) {
      q = q.or(`bill_no.ilike.%${search}%`);
    }
    return throwIf(await q);
  },

  async create(patientId, visitId, items, userId) {
    // Compute total
    const total = items.reduce((s, i) => s + (i.qty || 1) * i.unitPrice, 0);
    const bill = throwIf(
      await supabase.from('bills').insert([{
        patient_id: patientId,
        visit_id: visitId || null,
        total_amount: total,
        status: 'pending',
        created_by: userId,
      }]).select().single()
    );
    await supabase.from('bill_items').insert(
      items.map(i => ({
        bill_id:     bill.id,
        description: i.desc,
        category:    i.cat,
        quantity:    i.qty || 1,
        unit_price:  i.unitPrice,
      }))
    );
    return bill;
  },

  async recordPayment(billId, amount, method, referenceNo, userId) {
    await supabase.from('payments').insert([{
      bill_id: billId, amount, method,
      reference_no: referenceNo || null,
      received_by: userId,
    }]);
    // Recalculate paid_amount
    const { data: pmts } = await supabase.from('payments').select('amount').eq('bill_id', billId);
    const paidAmount = (pmts || []).reduce((s, p) => s + parseFloat(p.amount), 0);
    const { data: bill } = await supabase.from('bills').select('total_amount').eq('id', billId).single();
    const totalAmount = parseFloat(bill?.total_amount || 0);
    const newStatus = method === 'Waiver' ? 'waived' : paidAmount >= totalAmount ? 'paid' : 'partial';
    await supabase.from('bills').update({ paid_amount: paidAmount, status: newStatus }).eq('id', billId);
  },

  async todayRevenue() {
    const today = new Date().toISOString().slice(0, 10);
    const { data } = await supabase
      .from('bills')
      .select('paid_amount')
      .eq('status', 'paid')
      .gte('created_at', `${today}T00:00:00`);
    return (data || []).reduce((s, b) => s + parseFloat(b.paid_amount || 0), 0);
  },
};

// ═══════════════════════════════════════════════════════════════════
// HR / USERS
// ═══════════════════════════════════════════════════════════════════
export const hrService = {
  async list({ role = null, dept = null, search = '' } = {}) {
    let q = supabase
      .from('users')
      .select(`
        *,
        departments(name),
        user_roles(roles(name))
      `)
      .order('first_name');

    if (search) {
      q = q.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%,email.ilike.%${search}%,employee_no.ilike.%${search}%`);
    }
    return throwIf(await q);
  },

  async updateProfile(userId, payload) {
    return throwIf(
      await supabase.from('users').update(payload).eq('id', userId)
    );
  },

  async getDepartments() {
    return throwIf(await supabase.from('departments').select('*').order('name'));
  },
};

// ═══════════════════════════════════════════════════════════════════
// SETTINGS — system config stored in a simple kv table via metadata
// ═══════════════════════════════════════════════════════════════════
export const settingsService = {
  KEY: 'hms_settings',

  load() {
    try {
      return JSON.parse(localStorage.getItem(this.KEY) || 'null') || {};
    } catch { return {}; }
  },

  save(obj) {
    localStorage.setItem(this.KEY, JSON.stringify(obj));
  },
};
